### ISSUE TITLE
Crawling

### ISSUE THREAD

**Issue by choijaewoong24** [2021-SMHRD-KDT-Bigdata-3/suge#3]
스팀 홈페이지에서 태그들과 
전체적인 게임 정보와 이미지 크롤링하는 작업

일본어, 중국어, 특수문자 인코딩 모르겟어요

**Comment by kyg4914** [comment]
utf8로 인코딩 방식 지정후 파일 확인시에는 메모장으로 확인(엑셀의 기본 인코딩방식과 맞지 않아 엑셀에서는 한글이 깨질것)
